services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - mysql
    environment:
      - FLASK_ENV=development
    
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 2741
      MYSQL_DATABASE: gs25_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql  # 이 줄 추가
volumes:
  mysql_data:
